import type { Locale } from './i18n';

type GuideText = {
  title: string;
  description: string;
  problem: string;
  fix: string[];
  bad: string;
  good: string;
  highlight: string;
};

export type Guide = {
  slug: string;
  ruleSlug?: string;
  text: Record<Locale, GuideText>;
};

export const guides: Guide[] = [
  {
    slug: 'validate-ssh-config',
    text: {
      en: { title: 'How to validate ~/.ssh/config', description: 'Check an OpenSSH client config for semantic mistakes, local file problems, and Include errors before connecting.', problem: 'OpenSSH often accepts a file even when later settings are ineffective, unsafe, or point to missing files. A successful connection is not a complete validation.', fix: ['Paste the config into the private browser checker for a quick content check.', 'Run sshconfig-lint ~/.ssh/config for Include and IdentityFile checks.', 'Use ssh -G your-host to inspect the final values OpenSSH applies.'], bad: 'Host *\n  User deploy\n\nHost work\n  User alice', good: 'Host work\n  User alice\n\nHost *\n  User deploy', highlight: 'Host *' },
      de: { title: 'So prüfst du ~/.ssh/config', description: 'Prüfe eine OpenSSH-Client-Konfiguration vor der Verbindung auf logische Fehler, lokale Dateien und Include-Probleme.', problem: 'OpenSSH akzeptiert oft Dateien, obwohl spätere Werte wirkungslos, unsicher oder mit fehlenden Dateien verknüpft sind. Eine erfolgreiche Verbindung ist keine vollständige Prüfung.', fix: ['Füge die Config für eine schnelle Inhaltsprüfung in den privaten Browser-Checker ein.', 'Führe sshconfig-lint ~/.ssh/config für Includes und IdentityFiles aus.', 'Kontrolliere mit ssh -G dein-host die tatsächlich angewendeten Werte.'], bad: 'Host *\n  User deploy\n\nHost work\n  User alice', good: 'Host work\n  User alice\n\nHost *\n  User deploy', highlight: 'Host *' },
      fr: { title: 'Comment valider ~/.ssh/config', description: 'Vérifiez une configuration client OpenSSH avant la connexion, y compris les fichiers locaux et les Include.', problem: 'OpenSSH accepte souvent un fichier même si des valeurs sont inactives, risquées ou liées à des fichiers absents. Une connexion réussie ne suffit pas.', fix: ['Collez la configuration dans le vérificateur privé.', 'Exécutez sshconfig-lint ~/.ssh/config pour les Include et IdentityFile.', 'Contrôlez les valeurs finales avec ssh -G votre-hote.'], bad: 'Host *\n  User deploy\n\nHost work\n  User alice', good: 'Host work\n  User alice\n\nHost *\n  User deploy', highlight: 'Host *' },
      es: { title: 'Cómo validar ~/.ssh/config', description: 'Comprueba una configuración cliente OpenSSH antes de conectar, incluidos archivos locales e Include.', problem: 'OpenSSH suele aceptar un archivo aunque existan valores ineficaces, inseguros o rutas ausentes. Una conexión correcta no es una validación completa.', fix: ['Pega la configuración en el comprobador privado.', 'Ejecuta sshconfig-lint ~/.ssh/config para Include e IdentityFile.', 'Revisa los valores finales con ssh -G tu-host.'], bad: 'Host *\n  User deploy\n\nHost work\n  User alice', good: 'Host work\n  User alice\n\nHost *\n  User deploy', highlight: 'Host *' },
    },
  },
  {
    slug: 'check-ssh-config-syntax',
    text: {
      en: { title: 'Check SSH config syntax and behavior', description: 'Combine OpenSSH’s own parser with semantic linting instead of relying on a connection attempt.', problem: 'Syntax is only one layer. A directive can be valid but duplicated, shadowed by Host *, or dangerous when applied globally.', fix: ['Run ssh -G host to confirm OpenSSH can parse and expand the selected host.', 'Run sshconfig-lint to find structural and security mistakes.', 'Resolve every error first, then review warnings for intentional exceptions.'], bad: 'Host work\n  User deploy\n  User root', good: 'Host work\n  User deploy', highlight: 'User root' },
      de: { title: 'SSH-Config-Syntax und Verhalten prüfen', description: 'Verbinde den OpenSSH-Parser mit einer logischen Prüfung, statt dich auf einen Verbindungsversuch zu verlassen.', problem: 'Syntax ist nur eine Ebene. Eine gültige Direktive kann doppelt, durch Host * überstimmt oder global gefährlich sein.', fix: ['Prüfe mit ssh -G host, ob OpenSSH den gewählten Host auswertet.', 'Finde mit sshconfig-lint Struktur- und Sicherheitsfehler.', 'Behebe zuerst Fehler und prüfe danach jede Warnung auf eine beabsichtigte Ausnahme.'], bad: 'Host work\n  User deploy\n  User root', good: 'Host work\n  User deploy', highlight: 'User root' },
      fr: { title: 'Vérifier la syntaxe et le comportement SSH', description: 'Associez le parseur OpenSSH à une analyse sémantique au lieu de tester uniquement une connexion.', problem: 'La syntaxe n’est qu’une couche. Une directive valide peut être dupliquée, masquée par Host * ou dangereuse globalement.', fix: ['Utilisez ssh -G host pour évaluer l’hôte.', 'Utilisez sshconfig-lint pour la structure et la sécurité.', 'Corrigez les erreurs puis examinez chaque avertissement.'], bad: 'Host work\n  User deploy\n  User root', good: 'Host work\n  User deploy', highlight: 'User root' },
      es: { title: 'Comprobar sintaxis y comportamiento SSH', description: 'Combina el parser de OpenSSH con análisis semántico en vez de probar solo una conexión.', problem: 'La sintaxis es solo una capa. Una directiva válida puede estar duplicada, anulada por Host * o ser peligrosa globalmente.', fix: ['Usa ssh -G host para evaluar el host.', 'Usa sshconfig-lint para estructura y seguridad.', 'Corrige los errores y revisa después cada aviso.'], bad: 'Host work\n  User deploy\n  User root', good: 'Host work\n  User deploy', highlight: 'User root' },
    },
  },
  {
    slug: 'duplicate-host-blocks', ruleSlug: 'duplicate-host',
    text: {
      en: { title: 'Fix duplicate Host blocks in SSH config', description: 'Understand why repeated Host aliases are confusing and consolidate them without losing settings.', problem: 'Repeated Host patterns split one connection across several places. OpenSSH matching rules make it easy to edit a value that never becomes effective.', fix: ['Find both blocks reported as DUP_HOST.', 'Move the required directives into one block.', 'Remove the duplicate and confirm the result with ssh -G work.'], bad: 'Host work\n  User deploy\n\nHost work\n  Port 2222', good: 'Host work\n  User deploy\n  Port 2222', highlight: 'Host work' },
      de: { title: 'Doppelte Host-Blöcke beheben', description: 'Verstehe wiederholte SSH-Aliase und fasse sie ohne verlorene Einstellungen zusammen.', problem: 'Doppelte Host-Muster verteilen eine Verbindung auf mehrere Stellen. Dadurch bearbeitest du leicht einen Wert, der nie wirksam wird.', fix: ['Finde beide als DUP_HOST gemeldeten Blöcke.', 'Verschiebe benötigte Direktiven in einen gemeinsamen Block.', 'Lösche das Duplikat und prüfe mit ssh -G work.'], bad: 'Host work\n  User deploy\n\nHost work\n  Port 2222', good: 'Host work\n  User deploy\n  Port 2222', highlight: 'Host work' },
      fr: { title: 'Corriger les blocs Host dupliqués', description: 'Regroupez des alias SSH répétés sans perdre de réglages.', problem: 'Les motifs Host répétés répartissent une connexion dans plusieurs endroits et rendent certaines modifications inefficaces.', fix: ['Repérez les deux blocs DUP_HOST.', 'Déplacez les directives dans un seul bloc.', 'Supprimez le doublon et testez avec ssh -G work.'], bad: 'Host work\n  User deploy\n\nHost work\n  Port 2222', good: 'Host work\n  User deploy\n  Port 2222', highlight: 'Host work' },
      es: { title: 'Corregir bloques Host duplicados', description: 'Combina alias SSH repetidos sin perder ajustes.', problem: 'Los patrones Host repetidos reparten una conexión entre varios lugares y facilitan editar un valor ineficaz.', fix: ['Localiza los dos bloques DUP_HOST.', 'Mueve las directivas a un solo bloque.', 'Elimina el duplicado y prueba con ssh -G work.'], bad: 'Host work\n  User deploy\n\nHost work\n  Port 2222', good: 'Host work\n  User deploy\n  Port 2222', highlight: 'Host work' },
    },
  },
  {
    slug: 'host-wildcard-order', ruleSlug: 'wildcard-host-order',
    text: {
      en: { title: 'Put Host * in the correct order', description: 'Prevent broad SSH defaults from winning before a specific Host block is evaluated.', problem: 'For most settings, OpenSSH keeps the first obtained value. Host * near the top can therefore override a specific block below it.', fix: ['Move specific Host and Match blocks above the wildcard.', 'Keep shared defaults in Host * at the end.', 'Use ssh -G alias to confirm the effective User, HostName, and IdentityFile.'], bad: 'Host *\n  User deploy\n\nHost github.com\n  User git', good: 'Host github.com\n  User git\n\nHost *\n  User deploy', highlight: 'Host *' },
      de: { title: 'Host * richtig einordnen', description: 'Verhindere, dass breite SSH-Vorgaben vor einem konkreten Host gewinnen.', problem: 'OpenSSH behält für die meisten Einstellungen den ersten Wert. Host * am Anfang kann deshalb einen späteren konkreten Block überstimmen.', fix: ['Verschiebe konkrete Host- und Match-Blöcke nach oben.', 'Setze gemeinsame Vorgaben in Host * ans Ende.', 'Prüfe User, HostName und IdentityFile mit ssh -G alias.'], bad: 'Host *\n  User deploy\n\nHost github.com\n  User git', good: 'Host github.com\n  User git\n\nHost *\n  User deploy', highlight: 'Host *' },
      fr: { title: 'Placer Host * dans le bon ordre', description: 'Empêchez les valeurs générales de gagner avant un hôte précis.', problem: 'OpenSSH conserve généralement la première valeur. Host * placé en haut peut donc remplacer un bloc précis situé plus bas.', fix: ['Placez les blocs précis en premier.', 'Gardez Host * à la fin.', 'Vérifiez les valeurs avec ssh -G alias.'], bad: 'Host *\n  User deploy\n\nHost github.com\n  User git', good: 'Host github.com\n  User git\n\nHost *\n  User deploy', highlight: 'Host *' },
      es: { title: 'Colocar Host * en el orden correcto', description: 'Evita que valores generales ganen antes que un host específico.', problem: 'OpenSSH suele conservar el primer valor. Host * al principio puede anular un bloque específico posterior.', fix: ['Coloca primero los bloques específicos.', 'Deja Host * al final.', 'Comprueba los valores con ssh -G alias.'], bad: 'Host *\n  User deploy\n\nHost github.com\n  User git', good: 'Host github.com\n  User git\n\nHost *\n  User deploy', highlight: 'Host *' },
    },
  },
  {
    slug: 'ssh-include-cycle', ruleSlug: 'include-cycle',
    text: {
      en: { title: 'Find and break SSH Include cycles', description: 'Trace circular OpenSSH Include chains and move shared defaults into a one-way structure.', problem: 'A config can include a second file that eventually includes the first one again. The chain is difficult to inspect manually once globs and nested directories are involved.', fix: ['Start at the file and line reported as INCLUDE_CYCLE.', 'Follow the Include chain until it returns to an already visited file.', 'Remove that back-reference or move shared values into a third file included in one direction.'], bad: '# config\nInclude conf.d/work\n\n# conf.d/work\nInclude ../config', good: '# config\nInclude conf.d/work\n\n# conf.d/work\nInclude common.conf', highlight: 'Include ../config' },
      de: { title: 'SSH-Include-Zyklen finden und lösen', description: 'Verfolge kreisförmige Include-Ketten und ordne gemeinsame Vorgaben nur in eine Richtung.', problem: 'Eine Config kann eine Datei einbinden, die später wieder zur ersten zurückführt. Mit Globs und Unterordnern ist das manuell schwer zu erkennen.', fix: ['Beginne bei der als INCLUDE_CYCLE gemeldeten Datei und Zeile.', 'Verfolge die Kette bis zur bereits besuchten Datei.', 'Entferne den Rückverweis oder verschiebe gemeinsame Werte in eine dritte Datei.'], bad: '# config\nInclude conf.d/work\n\n# conf.d/work\nInclude ../config', good: '# config\nInclude conf.d/work\n\n# conf.d/work\nInclude common.conf', highlight: 'Include ../config' },
      fr: { title: 'Trouver et casser les cycles Include', description: 'Suivez une chaîne Include circulaire et organisez les valeurs communes dans un seul sens.', problem: 'Un fichier peut en inclure un second qui revient ensuite au premier. Les globs rendent cette boucle difficile à voir.', fix: ['Commencez à la ligne INCLUDE_CYCLE.', 'Suivez la chaîne jusqu’au fichier déjà visité.', 'Supprimez le retour ou déplacez les valeurs communes dans un troisième fichier.'], bad: '# config\nInclude conf.d/work\n\n# conf.d/work\nInclude ../config', good: '# config\nInclude conf.d/work\n\n# conf.d/work\nInclude common.conf', highlight: 'Include ../config' },
      es: { title: 'Encontrar y romper ciclos Include', description: 'Sigue una cadena Include circular y organiza los valores comunes en una sola dirección.', problem: 'Un archivo puede incluir otro que termina regresando al primero. Los globs dificultan ver el ciclo.', fix: ['Empieza en la línea INCLUDE_CYCLE.', 'Sigue la cadena hasta el archivo ya visitado.', 'Elimina el retorno o mueve los valores comunes a un tercer archivo.'], bad: '# config\nInclude conf.d/work\n\n# conf.d/work\nInclude ../config', good: '# config\nInclude conf.d/work\n\n# conf.d/work\nInclude common.conf', highlight: 'Include ../config' },
    },
  },
  {
    slug: 'identityfile-not-found', ruleSlug: 'identity-file-exists',
    text: {
      en: { title: 'Fix IdentityFile not found', description: 'Resolve missing SSH private-key paths without weakening file permissions or deleting valid host settings.', problem: 'A typo, moved key, or stale dotfiles path can leave a Host block pointing at a file that does not exist on the current machine.', fix: ['Expand ~ and inspect the exact path with ls -l.', 'Correct the path or provision the intended key for this machine.', 'Keep private keys readable only by their owner and rerun sshconfig-lint.'], bad: 'Host work\n  IdentityFile ~/.ssh/id_work_old', good: 'Host work\n  IdentityFile ~/.ssh/id_work_ed25519', highlight: '~/.ssh/id_work_old' },
      de: { title: 'IdentityFile not found beheben', description: 'Korrigiere fehlende SSH-Key-Pfade, ohne Dateirechte zu schwächen oder gültige Host-Einstellungen zu löschen.', problem: 'Ein Tippfehler, verschobener Schlüssel oder alter Dotfiles-Pfad kann auf eine Datei zeigen, die auf diesem Rechner nicht existiert.', fix: ['Löse ~ auf und prüfe den exakten Pfad mit ls -l.', 'Korrigiere den Pfad oder stelle den vorgesehenen Schlüssel bereit.', 'Lasse private Keys nur für ihren Besitzer lesbar und prüfe erneut.'], bad: 'Host work\n  IdentityFile ~/.ssh/id_work_old', good: 'Host work\n  IdentityFile ~/.ssh/id_work_ed25519', highlight: '~/.ssh/id_work_old' },
      fr: { title: 'Corriger IdentityFile introuvable', description: 'Corrigez un chemin de clé SSH absent sans affaiblir les permissions.', problem: 'Une faute, une clé déplacée ou un ancien chemin peut viser un fichier absent de cette machine.', fix: ['Développez ~ et inspectez le chemin avec ls -l.', 'Corrigez le chemin ou installez la clé prévue.', 'Gardez la clé lisible uniquement par son propriétaire et relancez le linter.'], bad: 'Host work\n  IdentityFile ~/.ssh/id_work_old', good: 'Host work\n  IdentityFile ~/.ssh/id_work_ed25519', highlight: '~/.ssh/id_work_old' },
      es: { title: 'Corregir IdentityFile no encontrado', description: 'Corrige una ruta de clave SSH ausente sin debilitar permisos.', problem: 'Un error, una clave movida o una ruta antigua puede apuntar a un archivo que no existe en este equipo.', fix: ['Expande ~ y revisa la ruta con ls -l.', 'Corrige la ruta o instala la clave prevista.', 'Mantén la clave legible solo por su propietario y ejecuta el linter otra vez.'], bad: 'Host work\n  IdentityFile ~/.ssh/id_work_old', good: 'Host work\n  IdentityFile ~/.ssh/id_work_ed25519', highlight: '~/.ssh/id_work_old' },
    },
  },
];

export const guideBySlug = (slug: string) => guides.find((guide) => guide.slug === slug);
