export const ruleSlugByCode: Record<string, string> = {
  INVALID_VALUE: 'invalid-directive-value',
  DUP_DIRECTIVE: 'duplicate-directives',
  DUP_HOST: 'duplicate-host',
  INCLUDE_CYCLE: 'include-cycle',
  INCLUDE_GLOB: 'include-glob',
  INCLUDE_NO_MATCH: 'include-no-match',
  INCLUDE_READ: 'include-read',
  INSECURE_OPT: 'insecure-option',
  MISSING_IDENTITY: 'identity-file-exists',
  MISSING_CERTIFICATE: 'certificate-file-exists',
  NEGATED_HOST: 'negated-only-host',
  PROXY_CONFLICT: 'proxy-command-jump-conflict',
  REVOKED_HOST_KEYS_UNREADABLE: 'revoked-host-keys-readable',
  LOCAL_COMMAND_DISABLED: 'local-command-enabled',
  INVALID_TOKEN: 'invalid-percent-token',
  UNSAFE_CTRL_PATH: 'unsafe-control-path',
  WEAK_ALGO: 'deprecated-weak-algorithms',
  WILDCARD_ORDER: 'wildcard-host-order',
};
